### ISSUE TITLE
Ethstats network we are waiting! 

### ISSUE THREAD

**Issue by zrock23** [eth-clients/sepolia#2]
So far this project is amazing I think you need to add ethstats network!  Good luck! 🤗

**Comment by DaveyD233** [comment]
The problem is NOT the Hysterium of ETHERIUM being #blocked, more than the #number#s of "POSSIBLE Ethereum 1&2 tokens", according to CoinBase, keeps rising 100k ETH1(&2.0) tokens since the BEGINNING of this year(ie. 120million ETH 1&2 tokens available, ON January 2022, to 120.1 ETH1&2 tokens IN February 2022, to NOW; Where there ARE 120.8Million ETH1(&2.0) tokens NOW, May 2022, EQUALLING "121.6 TOTAL ETH1&2.0 tokens" Today, but Eth 2.0 is STILL Not even available to use yet!? 
     Appearing as if ETHERIUM 2.0 is EQUALLY being "staked" is a RIP-OFF! Not only that, the increase of NOW 1.8MILLION MORE of Both ETHERIUMS 1&2, is making MY Current ETHERIUM 1 tokens depreciate in value!! 
     ADDING TWICE AS MANY tokens to "Balance out"_"APPEAR" as if ETH1&2 ARE Equal, while the "staked" ETH2.0 CAN'T Even be Touched, is the BIGGEST RIP OFF I HAVE EVER SEEN IN MY LIFE! WHO KEEPS ADDING THESE "NEW TOKENS" CoinBase is reporting, FOR BOTH ETHERIUM 1&2.0?! 

Thank you for your time, 
CAPT David Simonton-Valento, O-3_USAF, AAS, BT-BAS, Sap-Certification

**Comment by q9f** [comment]
Feel free to host one: https://github.com/goerli/ethstats-server

**Comment by xivanc** [comment]
@q9f @zrock23 I took the liberty to host it here https://stats.noderpc.xyz/ , if you'd like to add your instance feel free to DM me at daniel@noderpc.xyz for a secret key. Or I can share it here, if you prefer?

**Comment by q9f** [comment]
added to the readme, thanks!
