### ISSUE TITLE
Sepolia Faucet

### ISSUE THREAD

**Issue by devevmeth** [eth-clients/sepolia#75]
Hi @pk910 , @q9f 
Many thanks to the team for creating the Sepolia testnet so projects can test.

Sorry for this, currently I'm migrating dapps from the discontinued goerli testnet to the sepolia network.

Currently I have deployed contract tokens such as:
-USDC: 0x1d11B87Cccb6688f9f43A82F8B6743B7a8DA8e0a
-DAI: 0xD946B8511966f57F70Cc745D43D8d09Be2466630

Can you give me 12k native ETH so I can add liquidity under test net Sepolia and distribute to users?

 My wallet address: 0x8B3AbB8061B8F33bA988FB74489E5AC501DDaF05

Thank you very much, have a nice day.

**Comment by pk910** [comment]
Heya @devevmeth,

Thank you for your involvement with the Sepolia testnet and for transitioning your dApps from the Goerli testnet.

Regarding your request for 12k native ETH to add liquidity: It's important to note that the primary purpose of a testnet like Sepolia is to facilitate application testing, not trading or market operations. Consequently, providing liquidity for test tokens doesn't align with the intended use of testnets.

Since every developer has the ability to deploy their own token contracts as needed on the testnet, there is no essential requirement for specific liquidity setups. This flexibility allows each developer to create and test various scenarios independently.

It’s also worth noting that for deployments and testing, the funds provided by existing faucets on the testnet are usually more than sufficient. These faucets are designed to ensure developers have the necessary resources to test their applications thoroughly without the need for large amounts of testnet ETH for liquidity purposes.

We encourage you to continue testing your applications and to utilize the testnet for deploying and experimenting with smart contracts and dApps functionalities without the need for an established liquidity pool.

Thank you for your understanding and continued support of the testnet environment.

Have a great day!

**Comment by devevmeth** [comment]
Hi @pk910 
Thank you for your sharing. 
For 12k ETH, adding liquidity is only about 2k. 
For the remaining 10k we will create a faucet so users can get free ETH for testing, this faucet will work throughout and never run out.  It not only provides native tokens but also ERC20 tokens for users to test dapps under testnet.  I know we can get ETH from faucets but the small amount of ETH makes development limited.  Looking forward to your help so that we can carry out the provision of net test faucets. 
Thank you very much!

**Comment by devevmeth** [comment]
Please help me @q9f!, @pk910

**Comment by devevmeth** [comment]
Thanks!
